Made the spawning process agnostic to user shell by wrapping in bash -c
NERSC/sshspawner pull request #4
Opened 2017-09-07 02:59 UTC by shreddd

This is a somewhat tricky bug. We basically need to wrap everything in `bash -c 'command'`. The tricky thing about bash -c is that that actual command has to be in "" with all the bash redirection outside the double quotes.
eg.
```
bash -c '"ls -la" < /dev/null >> out.txt'
```

2017-09-07 03:00 UTC, shreddd commented
Also note that I've tested the pieces standalone, but this still needs to be tested with notebook spawning

2017-09-07 03:01 UTC, shreddd commented
fixes #1

2017-09-22 03:06 UTC, rcthomas commented on version.py
> +    2,
Increment to 0.0.3?

2017-09-22 03:08 UTC, rcthomas requested changes
Looks OK, I've tested.  One minor request.

2017-09-22 15:25 UTC, rcthomas commented
Additional comment: Noticed that the script generated is going to mess up the first setting, since there isn't a carriage return between the shebang and the first setting:

    #!/bin/bashexport PATH=/global/common/cori/software/python/3.6-anaconda-4.4/bin/:/global/common/cori/das/jupyterhub/:/usr/common/usg/bin:/usr/bin:/bin

Is in my /tmp file.

2017-09-22 18:45 UTC, rcthomas approved these changes

2017-09-22 18:45 UTC, merged